services:
  - type: web
    name: parking-lot-app
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: your-render-db-host
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: reservation
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: YourNewPassword123!
      - key: PORT
        value: "8080"
      - key: SPRING_PROFILES_ACTIVE
        value: render

