services:
  - type: web
    name: parking-lot-app
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/parking-lot-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
